name: erc4337
plugins:
  - name: solidity
    version: 0.6.1
dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.6.0
solidity:
  import_remapping:
    - "@openzeppelin/contracts=OpenZeppelin/4.6.0"
hardhat:
  port: 8555
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy
        enable_hardhat_deployments: true
