name: erc4337
plugins:
  - name: solidity
    version: 0.6.1
dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.4.2
solidity:
  import_remapping:
    - "@openzeppelin=OpenZeppelin/4.4.2"
